import tkinter as tk
from tkinter import ttk
from tkinter import messagebox as mbox
def calif():
    if(p1.get()!="" and p2.get()!="" and p3.get()!="" and opcion1!=0):
        puntaje=0
        if(p1.get()=="Mujer"): puntaje+=20
        if(p2.get()=="Liberen a willy"): puntaje+=20
        if(p3.get()=="2000"): puntaje+=20
        if(opcion1!=)
        cal="La puntuacion es: "+str(puntaje)
        mbox.showinfo("Calificacion",cal)
    else: mbox.showinfo("Advertencia", "Llene todos los campos")
ventana=tk.Tk()
ventana.title("Examen Literatura Mexicana")
p1=tk.StringVar()
p1_1=ttk.Entry(ventana, textvariable=p1)
tk.Label(ventana, text="¿Frida Khalo es hombre o mujer?").grid(column=0, row=0)
p1_1.grid(column=1, row=0)
p2=tk.StringVar()
p2_2=ttk.Entry(ventana, textvariable=p2)
tk.Label(ventana, text="¿Libro que trata sobre liberar una ballena de nombre willy?").grid(column=0, row=1)
p2_2.grid(column=1, row=1)
p3=tk.StringVar()
p3_3=ttk.Entry(ventana, textvariable=p3)
tk.Label(ventana, text="¿Año que se estrenó un libro despues del año 1999?").grid(column=0, row=2)
p3_3.grid(column=1, row=2)
tk.Label(ventana, text="Parte Final Harry").grid(column=0, row=5)
opcion1=tk.IntVar()
cas1=tk.Checkbutton(ventana, text="Caliz del Fenix", variable=opcion1)
cas1.grid(column=0, row=6, sticky=tk.W)
opcion2=tk.IntVar()
cas2=tk.Checkbutton(ventana, text="Piedra Filosofal", variable=opcion2)
cas2.grid(column=1, row=6, sticky=tk.W)
opcion3=tk.IntVar()
cas3=tk.Checkbutton(ventana, text="Reliquias de la muerte 2", variable=opcion3)
cas3.grid(column=2, row=6, sticky=tk.W)
opcion4=tk.IntVar()
cas4=tk.Checkbutton(ventana, text="Orden fenix", variable=opcion4)
cas4.grid(column=3, row=6, sticky=tk.W)
opcion5=tk.IntVar()
cas5=tk.Checkbutton(ventana, text="Primera parte", variable=opcion5)
cas5.grid(column=4, row=6, sticky=tk.W)
tk.Label(ventana, text="Rey de Narnia:").grid(column=0, row=7)
op=tk.IntVar()
r1=tk.Radiobutton(ventana, text="Aslan", variable=op, value=1)
r1.grid(column=0, row=10, sticky=tk.W)
r2=tk.Radiobutton(ventana, text="Tigre toño", variable=op, value=2)
r2.grid(column=1, row=10, sticky=tk.W)
r3=tk.Radiobutton(ventana, text="Escanor", variable=op, value=3)
r3.grid(column=2, row=10, sticky=tk.W)
r4=tk.Radiobutton(ventana, text="chato", variable=op, value=4)
r4.grid(column=3, row=10, sticky=tk.W)
r5=tk.Radiobutton(ventana, text="Ganzo", variable=op, value=5)
r5.grid(column=4, row=10, sticky=tk.W)
button1=ttk.Button(ventana, text="Calificar", command=calif)
button1.grid(column=2, row=11)
ventana.mainloop()
